### PR TITLE
Testing new "docs" style of page

### PR DESCRIPTION
**Pull request by vsoch**
I'm not liking the Table of Contents on the top like this:

image

And the content sort of smooshed to the right - it's not open and readable as a docs site should be!

So here I'm prototyping two example pages - one has a sidebar (meaning the docs item has more than one page like this) and the other does not:

with sidebar:

image

without:

image

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
Examples in preview:

https://19-405219078-gh.circle-artifacts.com/0/rse-radiuss.github.io/example-sidebar/index.html
https://19-405219078-gh.circle-artifacts.com/0/rse-radiuss.github.io/example/index.html

**Comment by vsoch** [comment]
I think this would look much better for this page: https://github.com/rse-radiuss/ci/pull/7

**Comment by vsoch** [comment]
I'm also thinking we should replace the (currently unstyled) top level menu with a single level navigation that matches the other two column layout, e.g., this:

image

**Comment by vsoch** [comment]
okay here is an example I have locally 

image

Let me know if you like it better! It doesn't have nesting but it's a little cleaner looking.

**Comment by davidbeckingsale** [comment]
I think that last example is an improvement, for sure.

**Comment by vsoch** [comment]
Awesome me too! Just pushed those changes, and here are previews of with/without sidebars:

https://20-405219078-gh.circle-artifacts.com/0/rse-radiuss.github.io/example-sidebar/index.html
https://20-405219078-gh.circle-artifacts.com/0/rse-radiuss.github.io/example/index.html

@davidbeckingsale one thing I was thinking - we should make a jekyll theme that can be easily inserted in the docs sub page suites (e.g., like rse-radiuss/ci) so we aren't redundantly copy pasting the same template everywhere (and then needing to edit it everywhere!) I can manually make the changes to the ci repo since it's already live like that, but my next TODO will be to look into that.

**Pull request merged**
